### ISSUE TITLE
JSORC in production

### ISSUE THREAD

**Issue by ypkang** [Jaseci-Labs/jaseci#660]
We will be breaking down #600 into multiple PRs to have JSORC integrated into jaseci ecosystem for production usage.

The main parts are as follows:

- [x] Action yaml configs (#661)
- [x] JEE docker images and automation (#634)
- [ ] jaseci ai kit docker images with preloaded model files to avoid download 
- [x] various QoL improvement from (@marsninja ) (#632)
	* public login 
	* user create API
- [ ] ~~update the yaml file of all jaseci ai kits~~
- [x] jsorc APIs  (#661 #684)
- [x] jsorc testing infrastructure (#650)
- [x] prometheus API (#684)
- [x] jsorc action optimizers and action state manager  (#661 #684)
- [x] synthetic application jac programs.
- [ ] JSORC kube based tests in github actions
- [x] free memory after unload module (#704)

**Comment by ypkang** [comment]
This has been largely completed. A couple of the remaining items will be converted to individual issues.
